name: Build & Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
#  lint:
#    name: GO lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run linting
#        uses: golangci/golangci-lint-action@v2
#
#  cypress:
#    name: Cypress
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run cypress
#        run: |
#          docker-compose -f docker/docker-compose.ci.yml run cypress
  build:
    name: Build and deploy app to heroku
    runs-on: ubuntu-latest
#    needs: [ 'lint', 'cypress' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Container
        run: |
          docker build --no-cache --tag registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web -f docker/gitline/Dockerfile .
      - name: Login to Heroku Container registry
        run: docker login --username=${{ secrets.HEROKU_EMAIL }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
      - name: Push Container
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Push to Heroku
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web